# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nintendo Automation Workflow
on: [push]

jobs:
  build:
    name: Run Nintendo Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install TestCafe and Running Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests"
